# Step 1: Use an official Node image as a base
FROM node:20

# Step 2: Set the working directory in the container
WORKDIR /chess

# Step 3: Copy package.json and package-lock.json to the container
COPY package*.json .

# Step 4: Install dependencies
RUN npm install

# Step 5: Copy the rest of the application code
COPY . .

# Step 6: Expose the port the app runs on
EXPOSE 5173

# Step 7: Use live-polling for Docker and Windows filesystem real-time updates
ENV CHOKIDAR_USEPOLLING=true

# Step 8: Start the React development server
CMD ["npm", "run", "dev"]

# docker run -p 5173:5173 -v %cd%:/chess -v /chess/node_modules react-app